### ISSUE TITLE
UI-style guide

### ISSUE THREAD

**Issue by yahyabouhlal** [yahyabouhlal/Workflow#2]
@ziko1999  créer UI-style guide

**Comment by Zakaria-ELhaouari** [comment]
verfier averc moi UI sttyle guide
@ayoubessafi @OumaESS @yahyabouhlal 
now plz

**Comment by OumaESS** [comment]
@ziko1999 très bien tu as bien spécialisé les couleurs

**Comment by ayoubessafi** [comment]
we need other icongraphie like sketchup!

**Comment by Zakaria-ELhaouari** [comment]
@ayoubessafi  les icons est deja dans le fonte awesome 
pas un grand problem

**Comment by ayoubessafi** [comment]
okay man, let's go.
