### ISSUE TITLE
griid

### ISSUE THREAD

**Issue by Zakaria-ELhaouari** [yahyabouhlal/Workflow#7]
tout l'equipe travail avec le grid qui deja pusher

**Comment by yahyabouhlal** [comment]
D'accord

**Comment by ayoubessafi** [comment]
okay, good job.

**Comment by OumaESS** [comment]
Done @ziko1999

**Comment by achrafelhour** [comment]
ok monsieur scram

**Comment by Zakaria-ELhaouari** [comment]
good luck
@yahyabouhlal @ayoubessafi @OumaESS @achrafelhour
