### ISSUE TITLE
Creat Header and sidebar 

### ISSUE THREAD

**Issue by Zakaria-ELhaouari** [yahyabouhlal/Workflow#8]
Creat Header and sidebar  @ayoubessafi

**Comment by ayoubessafi** [comment]
@ziko1999 @yahyabouhlal @OumaESS @achrafelhour svp verfiez avec mois 1ére étape de mon tache!

**Comment by achrafelhour** [comment]
monsieur ayoub good job 3andek wahad prime fi la fin de mois (^_^)
